### ISSUE TITLE
Please explain what do you mean by "/path/to/swagger-codegen-distribution"

### ISSUE THREAD

**Issue by hegdeaditya** [phiz71/vertx-swagger#1]
In the command "java -cp /path/to/swagger-codegen-distribution:/path/to/vertx-swagger-codegen-1.0.0-SNAPSHOT.jar io.swagger.codegen.SwaggerCodegen -l java-vertx -o ./test -i path/toSwagger/definition --group-id your.group.id --artifact-id my.api.vertx", Please explain what do you mean by "/path/to/swagger-codegen-distribution"

**Comment by phiz71** [comment]
"/path/to/swagger-codegen-distribution" means path to the swagger "cli" jar.
You can found it [here](https://github.com/swagger-api/swagger-codegen/tree/master/modules)

I've corrected the README.md, since the command was incomplete (missing the word "generate").
Hope it helps you.

**Comment by hegdeaditya** [comment]
@phiz71 yes I found that the word "generate" was missing later. Thanks for updating the README.md, its much intelligible now. Thanks again!!
