### ISSUE TITLE
Send Error Message As Json

### ISSUE THREAD

**Issue by nitish24p** [phiz71/vertx-swagger#109]
Currently when i get an exception, i end up sending the error message as a status message, and not as response body or json, attaching screen shot for reference, How do i send the error message as json in the response
<img width="1018" alt="Screen Shot 2019-08-02 at 7 11 47 PM" src="https://user-images.githubusercontent.com/13037986/62374485-b54dc380-b559-11e9-961c-75b1a94134a9.png">

```java
@Override
    public void sendOtp(SendOtpRequest otpPostRequest, Handler<AsyncResult<ResourceResponse<SuccessResponse>>> handler) {
       if (StringUtils.isBlank(otpPostRequest.getMobileNo())) {
           handler.handle(Future.failedFuture(new OtpApiException(400, "Mobile number missing")));
           return;
       }

   ... Other Logic

```

Am i doing anything incorrect?

**Comment by phiz71** [comment]
Hi @nitish24p, the only way to send a JSON in the response body is to have your verticle complete successfully.
Then you can customize the status message and code of the http response by using specific header in your Verticle response.

You can have a look [here](https://github.com/phiz71/vertx-swagger/blob/11437ef9d1210f69b59386b75cc4467fc5e6c27e/modules/vertx-swagger-router/src/main/java/com/github/phiz71/vertx/swagger/router/SwaggerRouter.java#L155) :
```java
eventBus.<String> send(serviceId, message, deliveryOptions, operationResponse -> {
  if (operationResponse.succeeded()) {
    manageHeaders(context.response(), operationResponse.result().headers());
      if (operationResponse.result().body() != null) {
        context.response().end(operationResponse.result().body());
      } else {
        context.response().end();
      }
    } else {
      vertxLogger.error("Internal Server Error", operationResponse.cause());
    manageError((ReplyException)operationResponse.cause(), context.response());
  }
});
```
and [here](https://github.com/phiz71/vertx-swagger/blob/11437ef9d1210f69b59386b75cc4467fc5e6c27e/modules/vertx-swagger-router/src/main/java/com/github/phiz71/vertx/swagger/router/SwaggerRouter.java#L206)
```java
private static void manageHeaders(HttpServerResponse httpServerResponse, MultiMap messageHeaders) {
  if(messageHeaders.contains(CUSTOM_STATUS_CODE_HEADER_KEY)) {
    Integer customStatusCode = Integer.valueOf(messageHeaders.get(CUSTOM_STATUS_CODE_HEADER_KEY));
    httpServerResponse.setStatusCode(customStatusCode);
    messageHeaders.remove(CUSTOM_STATUS_CODE_HEADER_KEY);
  }
  if(messageHeaders.contains(CUSTOM_STATUS_MESSAGE_HEADER_KEY)) {
    String customStatusMessage = messageHeaders.get(CUSTOM_STATUS_MESSAGE_HEADER_KEY);
    httpServerResponse.setStatusMessage(customStatusMessage);
    messageHeaders.remove(CUSTOM_STATUS_MESSAGE_HEADER_KEY);
  }
  httpServerResponse.headers().addAll(messageHeaders);
}
```

**Comment by nitish24p** [comment]
Thanks
