### ISSUE TITLE
Consider publishing released versions in public Maven repository

### ISSUE THREAD

**Issue by inikolaev** [phiz71/vertx-swagger#13]
It would be really great to publish library in some public Maven repository.

I saw many projects use [BinTray](https://bintray.com) - there's a way to create account for OpenSource - https://bintray.com/signup/oss

**Comment by phiz71** [comment]
I agree ! I had a look at [Official Central Repository](http://central.sonatype.org/pages/ossrh-guide.html). It's also free for opensource project.

But for the moment, I prefer spend the little time I have to improve SwaggerRouter and then adapt the codegen plugin.
And, by the way, I appreciate your contributions on the Router 👍

**Comment by inikolaev** [comment]
I also looked at the official one, but the process seemed to be a bit more involving.

The reason I'm asking is that we use router in our project and it would be more convenient to fetch stable dependency directly from Maven. Right now we had to copy source code into our project.

**Comment by phiz71** [comment]
Oh, I see. Well, I can't promise anything but maybe I can change my priorities ;)

**Comment by inikolaev** [comment]
No pressure :)

**Comment by phiz71** [comment]
Hi,
I've finally managed to publish the first SNAPSHOT version of the project.
https://oss.sonatype.org/content/repositories/snapshots/com/github/phiz71/vertx-swagger-router/

The release is coming soon. ;)

**Comment by phiz71** [comment]
[First official release](https://repo1.maven.org/maven2/com/github/phiz71)
