### ISSUE TITLE
Runtime compatibility to swagger codegen 2.2.2 broken

### ISSUE THREAD

**Issue by loeti** [phiz71/vertx-swagger#15]
With https://github.com/swagger-api/swagger-codegen/pull/4326 the CodegenModel class of swagger-codgen has changed. (**Boolean** object properties have been replaced by the primitive counterpart **boolean**)

<swagger-codegen.version>2.2.1</swagger-codegen.version> => ok
<swagger-codegen.version>2.2.2</swagger-codegen.version> => Runtime Error NoSuchFieldError: isEnum does not exist.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.296 s
[INFO] Finished at: 2017-03-07T17:37:47+01:00
[INFO] Final Memory: 16M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.swagger:swagger-codegen-maven-plugin:2.2.2:generate (vertx.server.stub) on project ebanking: Execution vertx.server.stub of goal io.swagger:swagger-codegen-maven-plugin:2.2.2:generate failed: An API incompatibility was encountered while executing io.swagger:swagger-codegen-maven-plugin:2.2.2:generate: java.lang.NoSuchFieldError: isEnum

**Comment by phiz71** [comment]
Hi @loeti , I've created a dedicated branch on which I've upgraded swagger-codegen from 2.2.1 to 2.2.2.
However, vertx-swagger project still compile and I was able to generate my sample petstore server.

Could you explain what you are trying to do ?

**Comment by loeti** [comment]
Hi @phiz71 , 

- I checked out the master branch as it is with the swagger-codegen dependency 2.1.6 and build it. 
- Then I used resulting artifact in my vertx project which has a swagger-codegen dependency to 2.2.2. - Then the error occurred during the build.

I did not  know that you had a special branch for the 2.2.2 compatibility. Is there the swagger-codegen dependency set to 2.2.2? 

By the way, I wanna use your vertx-swagger to generate a rather complex rest api. Thank you for your the work you done. I see now other issues because the pet-store project has not the same complexity as mine project e.g. string enums or model objects referencing other model objects.

**Comment by phiz71** [comment]
In fact, I'ce created this branch when I saw your issue, because I wanted to test the latest version of swagger-codegen. I didn't commit anything yet, but once I've done this, you will be able to test your code.
Ok for you ?

**Comment by vietj** [comment]
uhhmmm sorry for that

**Comment by vietj** [comment]
let me know if there is a blocker for you

**Comment by loeti** [comment]
@phiz71  It's ok for me. Thanks
@vietj It is definitely no blocker.

**Comment by loeti** [comment]
The 2.2.2 compatibilty branch works now!
Thanks!
