### ISSUE TITLE
Generated XXXApiVerticle does not support primitive types

### ISSUE THREAD

**Issue by loeti** [phiz71/vertx-swagger#17]
In the SwaggerRouter class the path parameters are extracted and put on the vertx eventbus packed in a JsonObject. 
`...

JsonObject e = new JsonObject();
                operation.getParameters().forEach((parameter) -> {
                    String name = parameter.getName();
                    Object value = ((ParameterExtractor)PARAMETER_EXTRACTORS.get(parameter.getIn())).extract(name, parameter, context);
                    e.put(name, value);
                });`

If the value is not a JsonObject but a e.g. Long or String, the generated code fails with a ClassCastException. It expects a JsonObject. See:

 `{{{dataType}}} {{paramName}} = Json.mapper.readValue(message.body().getJsonObject("{{paramName}}").encode(), {{{dataType}}}.class);`

**Comment by loeti** [comment]
I fixed it with a custom apiVerticle.mustach template as follows:
`...

{{#isPrimitiveType}}
                {{#isString}}
                    {{{dataType}}} {{paramName}} = message.body().getString("{{paramName}}");
                {{/isString}}
                {{^isString}}
                    {{{dataType}}} {{paramName}} = Json.mapper.readValue(message.body().getString("{{paramName}}"), {{{dataType}}}.class);
                {{/isString}}
            {{/isPrimitiveType}}
            {{^isPrimitiveType}}
                {{{dataType}}} {{paramName}} = Json.mapper.readValue(message.body().getJsonObject("{{paramName}}").encode(), {{{dataType}}}.class);
            {{/isPrimitiveType}}
`

**Comment by phiz71** [comment]
Hello, I've done some corrections. If it is OK for you, I will merge the branch to master.

**Comment by loeti** [comment]
Sure! Thanks!

**Comment by phiz71** [comment]
Did you have time to test what I have committed ?

**Comment by loeti** [comment]
I test it.

**Comment by loeti** [comment]
I found 3 issues that I have to correct after a code generation with my project swagger file.

1. If the host is defined with a port number e.g. "localhost:18080" the generated "serverPort" property is ":18080". Fix as follow: 
private String extractPortFromHost(String host) {
        if (host != null) {
            int portSepratorIndex = host.indexOf(':');
            if (portSepratorIndex >= 0 && portSepratorIndex+1 < host.length()) {
                return host.substring(portSepratorIndex+1);
            }
        }
        return "8080";
    }
2. In the apiVerticle.mustach template you have to use "baseName" as key an "parameterName" as the java variable name. Otherwise you cannot find swagger model properties that begin with a uppercase letter. parameterName for "PetId" is "petId" but the key (baseName) to get the property out of the Json is "PetId".
3. If your model has a description in the swagger file. There will be still a ApiModel import which is unintended. I had to overwrite 
@Override
    public CodegenModel fromModel(String name, Model model, Map<String, Model> allDefinitions) {
        CodegenModel codegenModel = super.fromModel(name, model, allDefinitions);
        codegenModel.imports.remove("ApiModelProperty");
        codegenModel.imports.remove("ApiModel");
        codegenModel.imports.remove("JsonCreator");
        return codegenModel;
    }
The postProcessModelProperty method is called before the import is added. 

I hope this helps.

**Comment by phiz71** [comment]
Thanks a lot. Your feedbacks were very helpful.
I've just committed new modifications on [swagger-codegen-2.2.2-compatibility](https://github.com/phiz71/vertx-swagger/commits/swagger-codegen-2.2.2-compatibility) branch.

**Comment by loeti** [comment]
There will come more. Our project is slowly starting and we use swagger/vertx and your router/codegen as critical components. The plan is to have our own version in a private repo and a public fork of your projects where we push back our findings/extensions to you and the community.
