### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by hegdeaditya** [phiz71/vertx-swagger#2]
Hey @phiz71, Can you please tell me how to enable Cross Origin Resource Sharing (CORS) with your vertx Server generator? Looks the current routes wont support that.

**Comment by phiz71** [comment]
The router created by the following line in MainApiVerticle is a ```io.vertx.ext.web.Router```
```java
Router swaggerRouter = SwaggerRouter.swaggerRouter(Router.router(vertx), swagger, vertx.eventBus());
```
So you can add CorsHandler to it just after the previous line. 
I think this link could help you : [http://vertx.io/docs/vertx-web/java/#_cors_handling](http://vertx.io/docs/vertx-web/java/#_cors_handling)

**Comment by hegdeaditya** [comment]
@phiz71  Thanks!! Got it working :+1:
