### ISSUE TITLE
content-type information in response

### ISSUE THREAD

**Issue by r-winkler** [phiz71/vertx-swagger#28]
Is there a way to set the content-type for the response in the vertx-swagger-router? The swagger UI needs this information otherwise the response is not displayed, only "Unknown response type".

**Comment by phiz71** [comment]
Hi,
Not for the moment. But I think your question is related to #12.

Once SwaggerRouter is able to add headers from the message of the eventBus to the http response, you will be able to customize headers, and particulary add Content-Type headers.
Not too hard I think, but I need time to implement this and test it.

Stay tuned ! :)

**Comment by r-winkler** [comment]
Thanks that's great!
