### ISSUE TITLE
Make generated API classes asynchronous?

### ISSUE THREAD

**Issue by philippkumar** [phiz71/vertx-swagger#33]
Hi there,

I am just starting using vert.x, and I was very happy to see that you guys implemented a swagger code generator! This is very helpful.

This is more a question than an issue, so feel free to close. I am wondering why the generated APIs are synchronous. A generated verticle calls the API object's method and blocks until it completes, then replies to the eventbus message. Wouldn't it be much better and more the vert.x way to do that asynchronously? Aren't you otherwise blocking one of the event loops? Or did I miss something here?

In my use case, I want to contact a keycloak server from the API interface implementation to validate a token, using the vert.x OAuth2 API, which is of course also asynchronous. So blocking seems unacceptable here.

I have a fork of this project where I generate void-only methods in generated API classes and have `Handler<AsyncResult<ResultType>>` as last argument. Feel free to check it out.

It conflicts with what has been recently done in this repo regarding exception handling and error codes, but it should be easy to add something similar to the async approach, I might do that in the near future.

Cheers
Philipp

**Comment by phiz71** [comment]
Hello Philipp,

thank you for you question.
Actually, you're absolutely right. The generated API should not be synchronous. It's a beginner mistake ;)

I've started to fix it in the last release [1.1.0](https://github.com/phiz71/vertx-swagger/releases/tag/v1.1.0). You can use the "-DfutureGeneration=true" option with the codegen plugin to make your API returning Future<>. But it has to be improved.

I've a look at your code and I like what you've done. Maybe you could PR ? For the error handling I think of two options :
1. APIs don't throw any Exception, but cause asyncHandler failure with the right "cause"
2. APIs throw Exceptions (but I must admit I don't know if it's a good practice to mix throwing exception and asynchandlers)

**Comment by philippkumar** [comment]
Thanks for your response!

Interesting idea about returning a vertx Future. I had a quick look at the class and think it should work as well, so it is more a matter of preference. We can have the API methods return the Future and then, in our generated verticle, set a result handler (which is also `Handler<AsyncResult>`) of the future.

I had a look at the usual vertx APIs, though, and feel they are mostly using void methods with `AsyncResult` as callback parameters. See `AuthProvider.authenticate` for example: http://vertx.io/docs/apidocs/io/vertx/ext/auth/AuthProvider.html#authenticate-io.vertx.core.json.JsonObject-io.vertx.core.Handler-

So, I'd suggest to also go for this approach, which I am already following in my fork. Do you agree? The better approach IMHO is to return RX observables, but as RX is treated as an additional API in vertx rather than being the main one, it is probably better to provide a non-RX variant first.


As for exception handling, my current implementation does option (1) of the two variants you mentioned. So we can e.g. call `handler.handle(Future.succeededFuture(theResult))` or `handler.handle(Future.failedFuture(exception))` already. I think this makes more sense.

Option 2 does not work IMHO, as by the time the API method returns, we do not know if an exception occurred, yet.

What my implementation does not do, yet (but yours does) is to have status codes for the errors. Should I attempt to integrate that before opening a PR (might take me some time) or should we go for async first (so I immediately open a PR) and then sort out the status codes?

Let me know what you think about this and what you prefer. I will then be happy to open a PR.

**Comment by vietj** [comment]
+1 for rxified API

**Comment by loeti** [comment]
Our implementation of the generated service API returns a `Single` because our services do blocking HTTP calls. e.g. 
Generated service interface:
`Single<AccountStatement> getAccountStatement(AccountStatementQuery accountStatementQuery, ServiceContext ebankingContext);`

Implementation:
`public Single<AccountStatement> getAccountStatement(AccountStatementQuery accountStatementQuery, ServiceContext ebankingContext) {`
`        Handler<Future<AccountStatement>> getAccountStatement = res -> {  .... };`
`          return vertx.rxExecuteBlocking(getAccountStatement); }`

**Comment by phiz71** [comment]
IMHO, what can be easily done:
By default, the vertx-swagger-codegen generates API interface whose methods return `void` and accept a `Handler<AsyncResult>` as a parameter.
If the plugin is used with a specific parameter, let's say `-DrxInterface=true`, previous methods return `Observable<>` and don't have a callback parameter.

Regarding errors, API methods **never** throw an Exception but the handler or the observable can fail with a specific cause : a custome `Exception` containg a statusCode and a statusMessage, so the vertx-swagger-router can response with the right value.

@philippkumar : if you're ok, you can open a PR with what you did (+ errors ? :) ), and I will work on the RX option and the generation of Rxified API interface. (Will be my first step into Rx world :D )

**Comment by philippkumar** [comment]
@phiz71 
Sounds good! Give me a few days for my PR :-), will resolve the conflicts and use the API exception you generate.

An RX variant would be awesome, thanks for tackling this issue. We probably should return `Single<ResultType>` for now, though? The idea of returning a stream of multiple values might perspectively be interesting, to e.g. send partial data back to the client as it becomes available and only complete the response, i.e. close the connection, once the observable stream completes, but we'd have to think about this first, sounds like something for a later iteration.

**Comment by phiz71** [comment]
I don't know very well RX, and don't know yet the difference between Single, Observable and others stuffs... but the time will come :)
Ok for Single, I trust you ;)

**Comment by philippkumar** [comment]
A Single is a special observable that only emits one value as opposed to several values. If we allowed several values, we would have to keep the HTTP connection to the client open after the first item is emitted, as more results could follow.

That sounds complicated. A more natural first step is to map our non-RX callback (which is also only one value) to an RX Single, I think.

**Comment by phiz71** [comment]
What if the ResultType is a List ? Should I use Observble ? Or a Single<List<T>> ? Sounds weird to use a Single for a List...

**Comment by philippkumar** [comment]
We can certainly discuss, but I recommend `Single<List<Type>>`, yes.

As stated, if you used Observable, you would have to add logic to deal with the partial response you get from the API implementation, e.g. aggregating it somewhere until it is complete or, probably much better, sending it back immediately to the client and close the HTTP connection when we receive onCompleted from the observable. This is something that needs work and, more importantly more thought on if we really want to do that, I did not think about all the implications, yet.

It also adds complexity to the implementation of the generated API class, as it would need to send onCompleted of the Observable correctly.

Also, consider the following Swagger response definition, for e.g. a GET endpoint:
```
responses:
    200:
        description: The operation completed successfully.
        schema:
            type: array
            items:
                $ref: "#/definitions/User"
```

This will generate (after my PR is through):
`void getUsers(Handler<AsyncResult<List<User>>> handler);`

`Single<List<User>>` is the correct 1:1 mapping for that, and I recommend to implement that first before tackling the complexity of allowing several items to be emitted.

**Comment by phiz71** [comment]
Ok, thanks for the explanation.

**Comment by phiz71** [comment]
#34 & #36 : PR done.
@philippkumar : can you review please ?
