### ISSUE TITLE
Make the generation of MainApiVerticle optional

### ISSUE THREAD

**Issue by phiz71** [phiz71/vertx-swagger#37]

**Comment by lopesmcc** [comment]
I use the `.swagger-codegen-ignore` to avoid generating the MainApiVerticle.

**Comment by phiz71** [comment]
I want to prevent MainApiVerticle.java from being generated since the first use of the swagger-codegen.
As far as i know, `.swagger-codegen-ignore` is generated by the swagger-codegen. So you can't use this file before generating your server.
