### ISSUE TITLE
basePath is ignored

### ISSUE THREAD

**Issue by Lakshmihm** [phiz71/vertx-swagger#39]
Hi,

Nice project! We are looking to use this in our project

I have the basePath specified in my swagger.json
 basePath: /products/v1

However they seem to be ignored
For example I can access http://localhost:8080/list but http://localhost:8080/products/v1/list doesn't work

Could you please check this?

**Comment by phiz71** [comment]
Hello,

This bug was fixed by the #35.
As it was merged a few days ago, I think you should try to download the last version on master.

We could be able to release a new version soon.

**Comment by Lakshmihm** [comment]
That's great!

I will download the master and check
