### ISSUE TITLE
CORS filter configuration

### ISSUE THREAD

**Issue by Lakshmihm** [phiz71/vertx-swagger#40]
Hi,

I am trying to host the swagger.json through the swagger ui.
I have hosted an api which would return the swagger.json and I am trying to use in the swagger ui
But I am running into CORS issue

I tried setting this in the MainVerticle class 
swaggerRouter.route().handler(CorsHandler.create("*")
						.allowedMethod(io.vertx.core.http.HttpMethod.GET)
						.allowedMethod(io.vertx.core.http.HttpMethod.POST)
						.allowedMethod(io.vertx.core.http.HttpMethod.OPTIONS)
						.allowCredentials(true)
						.allowedHeader("Access-Control-Allow-Method")
						.allowedHeader("Access-Control-Allow-Origin")
						.allowedHeader("Access-Control-Allow-Credentials")
						.allowedHeader("Content-Type"));

But still no luck, I am running into the same issue. Any help around this is much appreciated. Thanks

**Comment by phiz71** [comment]
I think the vertx google group is more appropriate for this kind of question.
I've searched for CORS questions and found  [this one](https://groups.google.com/forum/#!searchin/vertx/CORS|sort:relevance/vertx/7KSJLABrcUc/XIdBI-hpnNoJ)

I think this answer could help you :

> Yes I did, and after trying things, I finally was able to fix the issue.
> 
> Here is my settings for anyone interested
> 
> ```java
> CorsHandler corsHandler = CorsHandler.create("http://10.0.6.110:8081");  //Wildcard(*) not allowed if allowCredentials is true
> 		corsHandler.allowCredentials(true);
> 		corsHandler.allowedMethod(HttpMethod.OPTIONS);
> 		corsHandler.allowedMethod(HttpMethod.GET);
> 		corsHandler.allowedMethod(HttpMethod.POST);
> 		corsHandler.allowedMethod(HttpMethod.DELETE);
> 		corsHandler.allowedHeader("Authorization");
> 		corsHandler.allowedHeader("www-authenticate");		 
> 		corsHandler.allowedHeader("Content-Type");
> 	
> 		router.route().handler(corsHandler);
> 		router.route().handler(CookieHandler.create());					  
> 		router.route().handler(SessionHandler.create(LocalSessionStore.create(vertx, SESSION, 10000)));					  
> 		router.route().handler(basicAuthHandler);
> 		router.route().handler(BodyHandler.create());	
>```

**Comment by Lakshmihm** [comment]
Thanks!. That worked!
