### ISSUE TITLE
Does it support generating the Swagger yaml from the already existing Router entries in Vert.x ? or it is currently generating the Server stub using the swagger-codegen only ? 

### ISSUE THREAD

**Issue by debashisdeb** [phiz71/vertx-swagger#42]
Does vert.x support annotation driven swagger yaml generation yet ? I need to integrate it into my Vert.x project, which already has all the api's developed, and would like to use some mechanism so as to generate the yaml for Swagger.

**Comment by phiz71** [comment]
Hello,
no this project has to be used in a "design first" approach to configure a `Router` and/or to generate a server stub with the Swagger-codegen plugin. You can't generate any documentation and this feature is not yet planned. 

However, I know it is discussed in Vertx google group  (I see you've already posted your question there) and in some Vert.x issues.
There is also a very good work done by @slinkydeveloper  to integrate the future OpenAPI v3 version into Vert.X Web :
* https://groups.google.com/forum/#!searchin/vertx-dev/gsoc$202017$20swagger%7Csort:relevance/vertx-dev/rU4FOhMBkFU/v813waHTAAAJ
* https://github.com/slinkydeveloper/vertx-web/tree/designdriven

**Comment by debashisdeb** [comment]
Thanks for the quick turn around from your side !
So may be I can write down my own annotations so as to work with Vert.x ? For each router which is handling a HTTP Request, I can have my annotations to generate the yml for swagger upon building up the project. I'll let you know if this happens to work, as I think, there will be json output of the initial build process and then I can feed that into the Swagger renderer.
