### ISSUE TITLE
rootPackage is not configurable

### ISSUE THREAD

**Issue by lopesmcc** [phiz71/vertx-swagger#46]
On the vertx-swagger-codegen, the `rootPackage` variable is used determine the root package of generated resources, and is not configurable. 
The packages for API and Model resources can be overriden using swagger's `modelPackage` and `apiPackage` parameters, but unfortunately `MainApiVerticle` and `MainApiException` package is impossible to change at the moment.

I'd propose to stop using `rootPackage`, and just use the three parameters that swagger provides: `modelPackage`, `apiPackage` and `invokerPackage`. I would change the `MainApiVerticle` and `MainApiException` classes to use the `invokerPackage` instead.

Would you like me prepare a PR with these changes?

**Comment by phiz71** [comment]
Well, i've never thought of that before. It sounds like a good idea.
Yes, you can prepare a PR :)
Thanks
