### ISSUE TITLE
query params are always got as string, type in swagger.json ignored

### ISSUE THREAD

**Issue by Lakshmihm** [phiz71/vertx-swagger#53]
Hi,
`  Item:
    type: object
    properties:
      itemId:
        type: string
      quantity:
        type: integer
        format: int32`

For this schema quantity is an integer, but it is parsed as string from swaggerRouter and we have to manually convert to int
It would be nice to honour the type parameter

**Comment by phiz71** [comment]
Hi,
Even if the type of the parameter was respected, the swaggerRouter would send the parameter as Json on the eventBus. So the consumer of the message would have to parsed it.
Using string for all parameters (except for Body) is just a lazy choice :sweat_smile: .

**Comment by Lakshmihm** [comment]
Thanks for the reply
Even if we get as json, it will be a json with integer values instead of strings
we could do jsonObject.getInteger whereas doing this on a string would fail. We would have to parse it as an integer before

I know it was a easier choice. It is just convenient to honour it in future so that we don't have to parse string in code.
