### ISSUE TITLE
Swagger-Codegen module fails to generate operation that consumes a list in the body parameter

### ISSUE THREAD

**Issue by lopesmcc** [phiz71/vertx-swagger#55]
Fails to generate operations that consume lists in the body parameter
i.e.: if the spec has something like:
```...
  /operation:
    put:
      parameters:
        - name: updateModel
          in: body
          schema:
            type: array
            items:
              type: string
...
```
This is because Swagger Codegen, for some reason, is not populating the "baseType" variable for body type parameters.

A quick fix is add the following code to the `JavaVertXServerGenerator.postProcessOperations()` method:
```
            (...)
            for (CodegenOperation operation : ops) {
                (...)
                if (operation.getHasBodyParam() && operation.bodyParam.isListContainer) {
                    operation.bodyParam.baseType = operation.bodyParam.items.items.datatype;
                }
            }
            (...)
```
Not pretty, but it works.

Unfortunately, as the code is right now, nested lists are not supported, but that is another issue...

**Comment by phiz71** [comment]
Hi,
I think I've found another way to fix it. #58 .
Could you have a look please ?
