### ISSUE TITLE
Considering using OpenAPI Specification 3.0.0

### ISSUE THREAD

**Issue by phiz71** [phiz71/vertx-swagger#76]

**Comment by javadch** [comment]
Thanks @phiz71 for all your efforts.
Any estimated day for the release of this feature?

**Comment by phiz71** [comment]
Hello,
thanks @javadch for you support. Unfortunately, I can't give you a date because for the moment, I haven't much time to spend on this project. (I work on my free time).
I would like to have a first version for the end of October, but I can't promise anything.

**Comment by javadch** [comment]
Thank you very much, I am using OAS 2 for now.

On Thu, Sep 28, 2017 at 10:13 PM, Florent Chamfroy <notifications@github.com

**Comment by Dutchboy** [comment]
I really am looking forward to your efforts to get it to v3!!!

**Comment by phiz71** [comment]
Since the new release of Vert.X officialy support OAS 3.0 (http://vertx.io/docs/vertx-web-api-contract/java/), I think I won't adapt Vertx-swagger project. Indeed, the new "OpenAPI" Router replace the vertx-swagger-router and a new vertx-swagger project would only consist in a new swagger-codegen plugin.

To scaffold a vert.x project with OAS 3.0, you can also use this : https://github.com/pmlopes/slush-vertx

**Comment by Dutchboy** [comment]
@phiz71 .... I think you're right... I missed the new 3.5.0 release....

So... I guess all your efforts in this project (vertx-swagger) are going to an end?...

**Comment by javadch** [comment]
Do you plan to use it the code-gen?

**Comment by phiz71** [comment]
As I said, the router aprt of this project will become useless with OAS 3.0 and Vertx 3.5.0.
However, I think I will continue the codegen part. But I will have to rewrite it almost from scratch since the new Router does not work like vertx-swagger-router.

To achieve this, I would like to start from an oas3 petstore specification (with as many feature as possible), try to implement an api with that specification without swagger-codegen and then, write the templates, based on the api

And, I think I will create another repository :)

**Comment by phiz71** [comment]
A lot of work ahead !! 😅

**Comment by javadch** [comment]
Is in it possible to only change the templates that generate the MainVerticle so that it is using the OAS3 Vertx router? I like all the stuff done for operation mounting, parameter extraction, header and response mgmt, etc.

**Comment by Dutchboy** [comment]
@phiz71 Hi Florent!

Since your last remark above, I've been trying slush-vertx but sorry, it simply does not work. It hangs all the time. It's simply is too immature. I would be immensely grateful if you would update your project to aos3 - the code generation part....

Kind regards, Bert

**Comment by javadch** [comment]
Hi @phiz71,
Any progress here?
Any plan to release OAS 3 and Vert.x 3.5 compatible code gen?

**Comment by rvansa** [comment]
Hi, I've just stumbled upon this (writing down OAS3 for an existing application and only then finding out that the codegen does not support that) and I would also love to see this working.
