### ISSUE TITLE
The generated MainVerticle's start mehtod always listens on port 8080

### ISSUE THREAD

**Issue by javadch** [phiz71/vertx-swagger#77]
It would be very useful to all passing port number as a parameter along pom, or better to read the port from a config file.
The generator can have a switch to read the port from a parameter, a config file, or the default.
Also, it can copy the config file to a generated directory so that the start the app can load it not only for the port but also for other configurations items.
The Swagger cod-gen command line allows for such a config file, the `-c config.json` in this command:

`java -cp swagger-codegen-cli-2.2.3.jar;vertx-swagger-codegen-1.0.0.jar io.swagger.codegen.SwaggerCodegen generate -l java-vertx -o gen -i swagger.json -c config.json`

**Comment by phiz71** [comment]
With the current code on master, if you generate a server stubs, a `run-with-config.sh` script and a `config.json` are also generated. The script contains the following code :
```bash
#!/bin/sh

export TARGET_OUTPUT="target"

if [ ! -d "$TARGET_OUTPUT" ]; then
    echo "Control will enter here if $TARGET_OUTPUT doesn't exist. Therefore build operation going to start."
    mvn clean install
fi

java -jar target/{{artifactId}}-{{artifactVersion}}-fat.jar -conf config.json
```
and the `config.json` :
```json
{
    "http.port" : 8080
}
```

Does it answer your question ?

**Comment by javadch** [comment]
I updated my maven to point to the master branch and used Jitpack to always get the latest, like this:

```json
  <repositories>
	<repository>
	    <id>jitpack.io</id>
	    <url>https://jitpack.io</url>
	</repository>  
  </repositories>
```
```json
          <dependency>
            <groupId>com.github.phiz71</groupId>
            <artifactId>vertx-swagger-codegen</artifactId>
            <version>master-SNAPSHOT</version>
            <scope>compile</scope>
          </dependency>
```

But I am getting the following error:

> Failed to execute goal io.swagger:swagger-codegen-maven-plugin:2.2.2:generate (default) on project server.pfa: Execution default of goal io.swagger:swagger-codegen-maven-plugin:2.2.2:generate failed: Plugin io.swagger:swagger-codegen-maven-plugin:2.2.2 or one of its dependencies could not be resolved: Could not find artifact com.github.phiz71:vertx-swagger-codegen:jar:master-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots)

Any idea what the problem can be?

**Comment by javadch** [comment]
tested. works.
