### ISSUE TITLE
Access to swagger spec object from all verticles

### ISSUE THREAD

**Issue by javadch** [phiz71/vertx-swagger#81]
In the generated code, the Swagger spec object is created as a member of the start method of the `MainApiVarticle` class. As done here: 
`Swagger swagger = new SwaggerParser().parse(readFile.result().toString(Charset.forName("utf-8")));`
In many places, it is needed to access this object. For example, I have a `SystemApiVerticle` that exposes information about the running system. One of the endpoints needs to get API name, version, and the tags to report them to the user.
Currently, I must to either repeat the above code in other places or override the `start` method to have the Swagger object and keep it for further use.
It would be good to make this object available to all other Verticles as well as service implementations.
A similar argument may go to the SwaggerRouter, but currently, I don't have a scenario that touches the router.

**Comment by phiz71** [comment]
#85 : PR pushed.
I've created a Singleton `SwaggerManager` which contains the `Swagger` instance. This singleton can be accessed everywhere in the code.
```java
...
//in MainApiVerticle
SwaggerManager.getInstance().setSwagger(swagger);
...

//elsewhere
SwaggerManager.getInstance().getSwagger().get_xxx_();
```

**Comment by javadch** [comment]
Approved!
