### ISSUE TITLE
The code-gen to have an option to generate JsonObjects for the Swagger definitions, instead of POJOs 

### ISSUE THREAD

**Issue by javadch** [phiz71/vertx-swagger#86]
I have a set of services that work with  MongoDB backend and receive native JSON data.
I want to send this data to the client, but because the Swagger definitions are generated as POJOs, I have to materialize the received JSON objects to Java classes. Later, in the Verticles, these Java objects are once more serialized as JSON and sent to the requesting client.  I suggest these two transformations are just waste of CPU and Memory! It would be good to have a switch to tell the code-gen to generate JsonObjects from the  Swagger definitions. In this case, instead of <Entity> e.g., User, Product, and Store, only JsonObject is used and passed between layers. Also, the Verticles do not need to convert POJOs to JSON and make them pretty before sending them to clients.
The same concept should apply to lists and arrays of objects.

**Comment by phiz71** [comment]
@javadch : I've tried to generate some JsonObject ;) but I don't know if it fits your needs. I've chosen to generate classes that extends JsonObject and contain static String to list all the allowed key.
For instance :
```java
@JsonInclude(JsonInclude.Include.NON_NULL) 
public class Category extends JsonObject {
  private static final String ID_KEY = "id";
  private static final String NAME_KEY = "name";

  public Category () {
  }

  public Category (JsonObject json) {
    this.put(ID_KEY, json.getLong(ID_KEY));
    this.put(NAME_KEY, json.getString(NAME_KEY));
  }

  public Category (Long id, String name) {
    this.put(ID_KEY, id);
    this.put(NAME_KEY, name);
  }

  @JsonProperty("id")
  public Long getId(){ 
    return this.getLong(ID_KEY);
  }
  public Category setId(Long id){
    this.put(ID_KEY, id);
    return this;
  }

  @JsonProperty("name")
  public String getName(){ 
    return this.getString(NAME_KEY);
  }
  public Category setName(String name){
    this.put(NAME_KEY, name);
    return this;
  }
}
```

I think I will have more difficulties with Classes that have others classes or list or enum.
Before going further, can you confirm I've understood what you meant ?

**Comment by javadch** [comment]
I see this as a solution in the right direction, provided that the verticles accept these objects and send them to clients without additional reformating, serialization, or conversion.

**Comment by phiz71** [comment]
@javadch : I finally manage to get my code working for this issue. Just add this option `jsonObjectModelGeneration=true`.
Can you try it ?

**Comment by javadch** [comment]
Sure, I test an report back.

**Comment by javadch** [comment]
I can checkout to the `86_PlainOldJsonObject` branch! Also, do not see it on Github! Have you pushed it?

**Comment by phiz71** [comment]
Yes it have been pushed yesterday.
https://github.com/phiz71/vertx-swagger/tree/86_PlainOldJsonObject
