### ISSUE TITLE
Add operationId into the RequestContext

### ISSUE THREAD

**Issue by myok12** [phiz71/vertx-swagger#91]
In my project, I have a middleware that inspects incoming requests and need to do decision making based on the specific operation being invoked: think about rate limiting, logging, etc. for all operations - I'd much rather use a middleware to do this for all operations without having to make the individual operation handlers more complex than they already are.

The problem is that the operationId is not currently available to the `configureMessage` (`Function<RoutingContext, DeliveryOptions>`) as the RequestContext doesn't have visibility into the operation. And although there's visibility into the operation in the `ServiceIdResolver`, it is being lost.

Without access to the operationId, it's really difficult to achieve this. Relying on paths is not simple as there's logic inside `SwaggerRouter` that I'll have to duplicate.

I think putting extra data on the RoutingContext before invoking `configureMessage.apply()`  would allow me to customize this into the `DeliveryOptions` as I deem fit (by providing a custom `configureMessage` param), while it wouldn't adversely affect other users (it will not be copied over into the default `new DeliveryOptions()`). If there might be more pieces of data in the future, perhaps we should namespace such params.

I would love to code a pull request for this, but wanted to make sure this requirement makes sense beforehand.

**Comment by phiz71** [comment]
Hello. 
If I undestand well, you need to know which "Operation" has been called when you are in the eventBus Consumer, don't you ?
If the answer is yes, then, you can call the `swaggerRouter` static method with an `OperationIdResolver`, the 'operationId' will be the address in the eventBus. 
So, when you are in your eventBus consumer, the address **is** the operationId.

Here are parts of the `SwaggerRouter` code. You can see the resolver and the way serviceId is used when sending a message on the eventBus
```java
//In OperationIdResolver
public class OperationIdServiceIdResolver extends DefaultServiceIdResolver {
    @Override
    public String resolve(HttpMethod httpMethod, String pathname, Operation operation) {
        if (StringUtils.isBlank(operation.getOperationId())) {
            return super.resolve(httpMethod, pathname, operation);
        }

        return operation.getOperationId();
    }
}

//in SwaggerRouter
[...]
public static Router swaggerRouter(Router baseRouter, Swagger swagger, EventBus eventBus) {
    return swaggerRouter(baseRouter, swagger, eventBus, new DefaultServiceIdResolver(), null);
}

public static Router swaggerRouter(Router baseRouter, Swagger swagger, EventBus eventBus, ServiceIdResolver serviceIdResolver) {
    return swaggerRouter(baseRouter, swagger, eventBus, serviceIdResolver, null);
}
[...]
private static void configureRoute(Route route, String serviceId, Operation operation, EventBus eventBus, Function<RoutingContext, DeliveryOptions> configureMessage) {
[...]
        route.handler(context -> {
            try {
[...]               
                eventBus.<String> send(serviceId, message, deliveryOptions, operationResponse -> {


```

And here you can see an extract of a Verticle in a sample server
https://github.com/phiz71/vertx-swagger/blob/master/sample/petstore-vertx-server/src/main/java/io/swagger/server/api/verticle/PetApiVerticle.java
```java
private static final String ADDPET_SERVICE_ID = "addPet";
[...]
vertx.eventBus().<JsonObject> consumer(ADDPET_SERVICE_ID).handler(addPetHandler);
```

I hope I did not misunderstood.

**Comment by myok12** [comment]
I take my request back.
I was incorrectly imagining I could get the operationId before the swagger-router's route's handler is being invoked, which is obviously not possible. I'll move my code into my handlers, where the operationId is available to me.
